### ISSUE TITLE
b站上看了up主的视频，很优秀。但是drools如何实现产品化，还是有点懵懂，希望up主下几期可以普及一下相关知识

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [hongwen1993/fast-drools-spring-boot-starter#1]
1.kie-server如何处理流式数据
2.fireUntilHalt()场景如何使用
3.kie-server的rest api进行规则的调用值得讲一下
4.某一fact通过了哪些rule，被哪些rule拒绝，这些执行结果如何返回？（drools自带接口，不需要用户自己实现的情况下）
5.如何实现完全摒弃java代码， 直接在rule文件定义相关类（毕竟如果需要写java的话，还是需要技术人员介入），当然rule里的declare可以实现，但是insert fact的时候，还是需要依赖类的实现代码

**Comment by hongwen1993** [comment]
1. stream模式下可以处理
2. 任务调度，例如timer，或滑动窗口
3. 视频里其实有相应的操作，虽然不完全相同，实际一个道理
4. 监听，视频有讲
5. 决策表，视频里有。
（总结：你根本没有好好看视频）

在 2019-12-04 15:58:51，"oushu1zhangxiangxuan1" <notifications@github.com> 写道：


1.kie-server如何处理流式数据
2.fireUntilHalt()场景如何使用
3.kie-server的rest api进行规则的调用值得讲一下
4.某一fact通过了哪些rule，被哪些rule拒绝，这些执行结果如何返回？（drools自带接口，不需要用户自己实现的情况下）
5.如何实现完全摒弃java代码， 直接在rule文件定义相关类（毕竟如果需要写java的话，还是需要技术人员介入），当然rule里的declare可以实现，但是insert fact的时候，还是需要依赖类的实现代码

**Comment by hongwen1993** [comment]
群里小伙伴看到了，说我太严格了，的确我可能有点严格，但是我觉得这样的论调是为关注我的人负责。最后，谢谢支持~有不懂的欢迎提问

**Comment by oushu1zhangxiangxuan1** [comment]
> 群里小伙伴看到了，说我太严格了，的确我可能有点严格，但是我觉得这样的论调是为关注我的人负责。最后，谢谢支持~有不懂的欢迎提问

哈哈， 多谢， 我当时2倍速看的， 可能的确漏了些东西， 回头有空再刷一遍

**Comment by oushu1zhangxiangxuan1** [comment]
> 1. stream模式下可以处理 2. 任务调度，例如timer，或滑动窗口 3. 视频里其实有相应的操作，虽然不完全相同，实际一个道理 4. 监听，视频有讲 5. 决策表，视频里有。 （总结：你根本没有好好看视频） 在 2019-12-04 15:58:51，"oushu1zhangxiangxuan1" <notifications@github.com> 写道： 1.kie-server如何处理流式数据 2.fireUntilHalt()场景如何使用 3.kie-server的rest api进行规则的调用值得讲一下 4.某一fact通过了哪些rule，被哪些rule拒绝，这些执行结果如何返回？（drools自带接口，不需要用户自己实现的情况下） 5.如何实现完全摒弃java代码， 直接在rule文件定义相关类（毕竟如果需要写java的话，还是需要技术人员介入），当然rule里的declare可以实现，但是insert fact的时候，还是需要依赖类的实现代码 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

诶对了，可能还得麻烦up主一下，这几问题都对应的视频的第几讲？

**Comment by hongwen1993** [comment]
你的问题主要集中在6,7,8,9讲

在 2019-12-05 14:44:58，"oushu1zhangxiangxuan1" <notifications@github.com> 写道：

stream模式下可以处理 2. 任务调度，例如timer，或滑动窗口 3. 视频里其实有相应的操作，虽然不完全相同，实际一个道理 4. 监听，视频有讲 5. 决策表，视频里有。 （总结：你根本没有好好看视频） 在 2019-12-04 15:58:51，"oushu1zhangxiangxuan1" notifications@github.com 写道： 1.kie-server如何处理流式数据 2.fireUntilHalt()场景如何使用 3.kie-server的rest api进行规则的调用值得讲一下 4.某一fact通过了哪些rule，被哪些rule拒绝，这些执行结果如何返回？（drools自带接口，不需要用户自己实现的情况下） 5.如何实现完全摒弃java代码， 直接在rule文件定义相关类（毕竟如果需要写java的话，还是需要技术人员介入），当然rule里的declare可以实现，但是insert fact的时候，还是需要依赖类的实现代码 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

诶对了，可能还得麻烦up主一下，这几问题都对应的视频的第几讲？

**Comment by SuperChrisliu** [comment]
有群吗，群二维码发一下

**Comment by heyaheng1995** [comment]
我收到了。看到后会尽快回复。

**Comment by hongwen19932** [comment]
有个 QQ 群 476067618
________________________________
发件人: chris ***@***.***>
发送时间: 2023年2月7日 15:36
收件人: hongwen1993/fast-drools-spring-boot-starter ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [hongwen1993/fast-drools-spring-boot-starter] b站上看了up主的视频，很优秀。但是drools如何实现产品化，还是有点懵懂，希望up主下几期可以普及一下相关知识 (#1)


有群吗，群二维码发一下

―
